---
# Begin of File
# For Dark SHINE Software
# Default Configuration by Yulei Zhang

# IMPORTANT: For yaml, indentation matters!

# material table
material_file: "material.yaml"

###########################################
# Geant4 General Settings
###########################################
verbosity:
  run: 2
  event: 0
  tracking: 0

random_seed:
  mode: "time" # "time" for current time seed, others for seed defined below
  seed: 10

general_particle_source:
  # Details for Geant4 general particle source settings
  settings:
    source/multiplevertex: true
    source/intensity: 5
    particle: "proton"
      # Energy Setting
      ene/mono: "250 MeV"
    #    ene/type: "Lin"
    #    ene/min: "50 MeV"
    #    ene/max: "150 MeV"
    #    direction: "0 0 1"
    #position: "0 0 -50 cm"
    # Square box
    pos/type: "Plane"
    pos/shape: "Rectangle"
    pos/centre: "0 0 -50 cm"
    pos/halfx: "1 cm"
    pos/halfy: "3 cm"
  # Number of particles emitted
  beam_on: 10

###########################################
# Global Variables
###########################################
# save geometry in the output root file
save_geometry: false
# check geometry overlap, maybe very slow
check_overlaps: false
# memory check
memory_check: false
# if to allow optical process
optical_simulation: false

###########################################
# Root Manager Settings
###########################################
RootManager:
  outfile_Name: "pct_out.root"
  tree_Name: "pct"

  # job run number
  Run_Number: 0
  # how many events in this run
  Total_Event_Number: 10000

###########################################
# Output Collection Settings
###########################################
OutCollection:
  # save all kinds of mc particles
  save_all_mcp: false
  # output collection name
  MCParticle_Name: "MCParticle"
  ParticleStep_Name: "Init_Particle_Step"

###########################################
# Detector Geometry
###########################################
Geometry:
  # Sensitive Detector Name
  ftrk_name: "FrontTracker"
  rtrk_name: "RearTracker"
  scintillator_name: "Scintillator"
  telescope_name: "Telescope"

  target_size: [ 10, "cm", 10, "cm", 4,"cm" ]
  target_material: "Water"
  # The offset from target for detectors (the radius of target circle)
  target_offset: [ 10, "cm" ]
  human_model:
    use_human_model: false
    directory: "./../Organism_Models"
    composition:
      - name: "liver"
        material: "Water"

  # Material Building
  world_material: "vacuum"

  # Tracker
  # --------
  # Front Tracker
  ftrk_material: "G4_Si"
  ftrk_strip_size: [ 2.5 , "mm", 10 , "cm", 0.1 , "mm" ] # size of one silicon strip
  ftrk_strip_arrangement: [ 61, 3, 1 ] # arrangement of one silicon strip
  ftrk_position:
    - [ 0 , "cm", 0 , "cm", -10 , "cm" ] # Layer 1
    - [ 0 , "cm", 0 , "cm",   0 , "cm" ] # Layer 2
    - [ 0 , "cm", 0 , "cm",  10 , "cm" ] # Layer 3
  # --------
  # Rear Tracker
  rtrk_material: "G4_Si"
  rtrk_strip_size: [ 2.5 , "mm", 10 , "cm", 0.1 , "mm" ] # size of one silicon strip
  rtrk_strip_arrangement: [ 61, 3, 1 ] # arrangement of one silicon strip
  rtrk_position:
    - [ 0 , "cm", 0 , "cm", -10 , "cm" ] # Layer 1
    - [ 0 , "cm", 0 , "cm",   0 , "cm" ] # Layer 2
    - [ 0 , "cm", 0 , "cm",  10 , "cm" ] # Layer 3

  # Calorimeter
  # material reference: https://www.crystals.saint-gobain.com/products/bc-408-bc-412-bc-416
  # --------
  # holder
  holder_material: "CarbonFiber"
  holder_gap: [ 1, "mm" ]
  # --------
  # wrapper
  wrapper_material: "G4_Al"
  wrapper_size: [ 0.1 , "mm", 0.1 , "mm", 0.1 , "mm" ]
  # --------
  # Scintillator
  scintillator_material: "G4_PLASTIC_SC_VINYLTOLUENE"
  scintillator_size: [ 60 , "cm", 101 , "cm", 3 , "mm" ] # size of cell
  scintillator_arrangement: [ 1, 1, 3 ]
  scintillator_offset: [ 5, "cm" ]
  # --------
  # Range Telescope
  telescope_material: "G4_PLASTIC_SC_VINYLTOLUENE"
  telescope_size: [ 63 , "cm", 101 , "cm", 3 , "mm" ] # size of cell
  telescope_arrangement: [ 1, 1, 42 ]
  telescope_offset: [ 5, "cm" ]


# End of File
---

